### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m3-evaluacion-intermedia-eva-lm#1]
Buen trabajo @eva-lm  !

Algunas pistas para acabarlo:

## React

- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa el `id` de cada pokemon para el `key` de react cuando mapeas y creas un listado de componentes
- [x] Mover `li` fuera del componente 'Pokemon', de esta manera es una tarjeta simple que podemos usar en cualquier lugar, no solo dentro de un 'ul` (opcional)
- [x] En el componente del listado hay que recorrer el array de pokemons que le llega por props y pintar una tarjeta por cada uno.
- [x] Termina de añadir los componentes finales: recuerda que **PokeList** suele contener la lista de elementos y **Pokemon** tendrá solo la tarjeta

## HTML

- [x] Revise los metadatos en index.html (lang, title ...)

## Otros

- [x] Elimina el código comentado que no aporte nada

Cuando tengas esto puedes:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by migueldelmazo** [comment]
Hola @eva-lm estoy revisando las issues y no me encaja las cosas que has marcado como terminadas con el código subido y la página publicada en GitHub Pages. Me puedes dar un poco de info de dónde has hecho las mejoras?

**Comment by eva-lm** [comment]
Ya está actualizado :)  no había subido los cambios sorry.
